name: Upload Blink to ESP32 via OTA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Install ESP32 core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Compile the sketch
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32 --output-dir ./build blink/blink.ino

      - name: Upload via OTA
        run: |
          arduino-cli upload --fqbn esp32:esp32:esp32 -p 192.168.0.168 ./build/blink.ino
